### PR TITLE
Sg/global spring 21 updates

### PR DESCRIPTION
**Pull request by schandlergarcia**
### What does this PR do?

Updates Ebikes to be compatible with the Spring '21 release by doing the following: 

1. Update API versions to 51.0
2. Update @salesforce/sfdx-lwc-jest to 0.10.4
3. Update .forceignore to the new “v2” format
    1. Add this line on top of the file: # .forceignore v2
    2. Update all glob patterns like **settings to **/settings/**
4. Remove “force” from sfdx force:auth commands (https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md)

## The PR fulfills these requirements:

[X] Tests for the proposed changes have been added/updated.
[X] Code linting and formatting was performed.

### Functionality Before

Ebikes was not up to date with the latest from Spring '21

### Functionality After

The app is now up to date!

### CODE REVIEW

**Comment by schandlergarcia** [comment]
The scratch org deploy is failing with this error `The request to create a scratch org failed with error code: VR-0003`

This seems to relate to this bug: https://github.com/forcedotcom/cli/issues/272 

@pozil have you seen this in other projects?

**Comment by pozil** [comment]
@schandlergarcia it's fixed.
I didn't see this issue with the other apps and I simply looked at the comments on the issue you've linked.
The solution was to get rid of the `"release": "Preview",` property in `sfdx-project.json`. BTW where did you find that? I've never seen this prop.

**Review by pozil — APPROVED** [review]

**Comment by schandlergarcia** [comment]
> @schandlergarcia it's fixed.
> I didn't see this issue with the other apps and I simply looked at the comments on the issue you've linked.
> The solution was to get rid of the `"release": "Preview",` property in `sfdx-project.json`. BTW where did you find that? I've never seen this prop.

Ahh Great, I thought we might need it for deploying the V51 components. You can find it [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_version_selection.htm), I always use it for testing changes in a preview scratch org.

**Comment by pozil** [comment]
Thanks for the doc link. That's news to me. This is great because it means that I can simplify the pre-release CI workflow by getting rid of our pre-release gs0 dev hub.

**Pull request merged**
