### PR TITLE
Winter ’21 Update

### PR DESCRIPTION
**Pull request by schandlergarcia**
### What does this PR do?

This PR Takes changes made for the Winter '21 Update and merges them into the master branch. These features include

In-App Guidance 
Dynamic Forms

### What issues does this PR fix or reference?

None

## The PR fulfills these requirements:

[X] Tests for the proposed changes have been added/updated.
[X] Code linting and formatting was performed.

### Functionality Before

We were missing these cool features!

### Functionality After

E-Bikes can now be deployed onto Winter '21 orgs.

### CODE REVIEW

**Comment by yasarshaikh** [comment]
@pozil  - Curious to know why navigationMenus is still part of mdapi menu? As per https://developer.salesforce.com/docs/metadata-coverage/50 it is supported in unlocked package as well.

**Comment by pozil** [comment]
Thanks @yasarshaikh, that's a good catch. We had some issues during the pre-release phase so we kept it there but we can move it now.

**Comment by yasarshaikh** [comment]
@pozil  - I have one more doubt(sorry for bothering again) - I see sites and siteDotComSites in force-app. Are they both not supposed to be same?

**Comment by pozil** [comment]
No worries, @yasarshaikh. The metadata from these two types is quite different but I'll admit that I don't know their exact purpose. There could be some leftovers from the time when this Community was not an ExperienceBundle.
@schandlergarcia any clue?

**Pull request merged**
