### PR TITLE
Adding LMS

### PR DESCRIPTION
**Pull request by pozil**

### CODE REVIEW

**Comment by muenzpraeger** [comment]
@schandlergarcia @pozil What's the issue with the failing CI?

**Comment by pozil** [comment]
@muenzpraeger this is due to the Community 226 regression we talked about in the email thread with engineering.
In short: deploying a LWC that's used both in LEX and in an experience bundle will crash.

**Comment by muenzpraeger** [comment]
@pozil I thought that was throwing a Gack, which isn't the case here.

**Comment by pozil** [comment]
@schandlergarcia did you get a chance to talk with the PM?

**Comment by pozil** [comment]
> @pozil I thought that was throwing a Gack, which isn't the case here.

Yes, it will throw a gack once you update the Community metadata. It's not done on this branch, see the Community update branch.

**Comment by schandlergarcia** [comment]
> @schandlergarcia did you get a chance to talk with the PM?

I chatted with him today and he is no longer looking after LAS.

**Pull request merged**
