### PR TITLE
Removed bike customizer component

### PR DESCRIPTION
**Pull request by pozil**
Addressed #94 by removing unmaintained component.

### CODE REVIEW

**Comment by pozil** [comment]
How about we get rid of that bike customizer @muenzpraeger?

**Comment by pozil** [comment]
@muenzpraeger can you please review this?

**Comment by muenzpraeger** [comment]
I would think we move it out/park it in it's own branch. Depending on how we move forward with the app this could be still a nice B2C/B2B UI feature.

**Comment by pozil** [comment]
No need for a branch because it's in revision control.
I just added a winter-20 tag so that we can go back to it if we ever want to get it back.

**Pull request merged**
